### ISSUE TITLE
Dashboard starts on wrong tab

### ISSUE THREAD

**Issue by EvanaHolevas** [CSCI-150-LAB/Team9Repo#12]
The dashboard should open on the "Dashboard" tab with the graphs, instead it opens on the "Health Summary" one. A default needs to be set.

**Comment by biyori** [comment]
My tabs don't even open??

**Comment by biyori** [comment]
Changed the default tab to be Dashboard

`private void Dashboard_Load(object sender, EventArgs e)
{
	//Set the dashboard tab to be displayed first
	tabControl1.SelectedIndex = 0;
}`
