### ISSUE TITLE
Dashboard graphs and "last 10 meals" needs to update after adding new foods

### ISSUE THREAD

**Issue by EvanaHolevas** [CSCI-150-LAB/Team9Repo#19]
Clicking save on the Add Foods tab needs to also prompt the graphs and recent meals to update their data

**Comment by EvanaHolevas** [comment]
The bar graph updates now only. The others are still being fixed.

**Comment by biyori** [comment]
[Fixed](https://github.com/CSCI-150-LAB/Team9Repo/commit/b2f490d57d90f357c6198fbd6cfdf8fd18c7881b)
